import fileName from './_fileNameConverter.js'
import hero from './katas/Is_he_gonna_survive.js'
import fixTheMeerkat from './katas/My_head_is_at_the_wrong_end.js'
import bonusTime from './katas/Do_I_get_a_bonus.js'
import {zeroFuel} from './katas/Will_you_make_it.js'
import bmi from './katas/Calculate_BMI.js'
import take from './katas/Enumerable_Magic_25_-_Take_the_First_N_Elements.js'
import twiceAsOld from './katas/Twice_as_old.js'